shell = "zsh"

[plugins]
[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"
use = [
    "lib/completion.zsh",
    "lib.sh",
    "lib/history.zsh",
    "plugins/git/git.plugin.zsh",
    "plugins/fzf/fzf.plugin.zsh"
]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"